### ISSUE TITLE
port 9000 

### ISSUE THREAD

**Issue by kz1000a1** [mOqOm/JP_Radio#3]
インストール、試用させていただきました。
localhost:9000 に relay させたストリーミングを再生する仕組みとお見受けしました。
Logitech Media Server plugin が既に 9000番ポートを使っているので共存できないとまずいのではないかと思います。
どうも Logitech Media Server は 9000 が使われていたら 9001 を使うのようになっているようです。ただしポートが変更されても plugin の設定からは 9000 ポートが決めうちで開かれます。
他のプラグインの事情や volumio のポリシーは分かりませんが、JP_Radiko としては 9000 は避ける。できれば設定からポートを変更できるようにしておくのが良さそうに思います。
とりあえず、JP_Radiko を 9001番に変更してLogitech Media Server と共存するところまで確認しました。

修正するスキルが無いので言うだけでがすいません。宜しくお願いします。

**Comment by mOqOm** [comment]
kz1000a1様
お世話になっております。
mOqOmです。

ご意見ありがとうございます！
kz1000a1様のおっしゃる通り、設定からポートを柔軟に設定できる方が他のプラグインとの共存ができますね。
あまりポート関連を意識せず決め打ちで行っていたので、ご意見助かります。

すぐに対応ができず大変心苦しいですが、次回のリリースで対応したいと思います。
しばらくお待ちいただければと思います。
よろしくお願いします。

**Comment by kz1000a1** [comment]
mOqOmさん
回答ありがとうございます。
日本の全 Volumio ユーザー待望のプラグインですからね。
たいへん期待しています。

**Comment by mOqOm** [comment]
kz1000a1様
お世話になっております。
mOqOmです。

まだバグがあるかもしれませんが取り急ぎ対応いたしました。
デフォルト値は9000のままですが、設定でウェルノウンポートを除く任意ポートで起動できるようにいたしました。
よろしくお願いいたします。
